spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://postgresql:5432/postgres
  data:
    redis:
      host: redis
      port: 6739

